# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformRating',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ratingValue', models.CharField(max_length=10)),
                ('platForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniBond.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionAgency',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('platForm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniBond.Platform')),
                ('promotionAgency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniBond.PromotionAgency')),
            ],
        ),
        migrations.CreateModel(
            name='RatingOrganization',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='platformrating',
            name='ratingOrganization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='miniBond.RatingOrganization'),
        ),
    ]
