# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0005_linktowx_idvalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linktowx',
            old_name='idValid',
            new_name='isValid',
        ),
        migrations.RenameField(
            model_name='promotioninfo',
            old_name='idValid',
            new_name='isValid',
        ),
        migrations.AddField(
            model_name='platform',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
