# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0006_auto_20170922_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniBond.LabelText'),
        ),
        migrations.AlterField(
            model_name='platformlabel',
            name='platForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniBond.Platform'),
        ),
    ]
