# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0008_clicktrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktowx',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
