# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0011_auto_20171016_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktowx',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/toWx'),
        ),
    ]
