# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0012_linktowx_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktowx',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/toWx'),
        ),
    ]
