# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0013_auto_20171016_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='comments',
            field=models.CharField(default='', max_length=30),
        ),
    ]
