# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0014_platform_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioninfo',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='platform',
            name='comments',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='platform',
            name='website',
            field=models.URLField(default=' '),
        ),
    ]
