# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBond', '0015_auto_20171204_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktowx',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
